export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function getRandomInt(max: number) {
  return Math.floor(Math.random() * max);
}

export default function ProductDetailRootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  const random = getRandomInt(2)
  
  if (random === 1) {
    throw new Error("Error loading page")
  }

  return (
      <>
        {children}
        <h2>This is review layout</h2>
      </>
  )
}
