import { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Kyutae",
    template: "%s | Company Name",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            padding: '1rem',
            backgroundColor: 'lightgray',
            textAlign: 'center',
          }}
          >header</header>
        {children}
        <footer
          style={{
            padding: '1rem',
            backgroundColor: 'lightgray',
            textAlign: 'center',
          }}
          >footer</footer>
      </body>
    </html>
  )
}
